Vladless/Solo_bot

handlers/notifications.py

Теперь при завершении пробного периода и доступном балансе пользователя ключ продлевается автоматически

Автопродление ключа

---

bot.py
handlers/admin.py
handlers/backup_handler.py
handlers/commands.py
handlers/trial_key.py
handlers/utils.py

Key_management.py разделен на два файла, раньше в него включались еще и обработчики. 
Исправлен недочет при котором команда /backup могла использоваться не админом

Порядок. Исправления мелких недочетов

---

bot.py
client.py
database.py
handlers/admin/admin.py

Админ сразу продлевает или уменьшает ключ в базах данных панели и бота

Админ. Установка времени ключей

---

bot.py
handlers/admin/admin.py
handlers/admin/admin_panel.py
handlers/admin/user_editor.py
handlers/commands.py
handlers/notifications.py

Теперь вместо прямых команд можно использовать интерфейс админа в боте:
- статистика пользователей
- сервер пользователя
- ключ пользователя
- удаление ключа пользователя
- изменение времени истечения ключа пользователя

/admin. GUI интерфейс в боте

---

handlers/keys/keys.py
handlers/start.py

При смене локации и выдаче пробного ключа можно нажать на кнопку, которая автоматически добавит ключ в клиентское приложение

Кнопка автодобавления конфигурации в клиентское приложение

---

install.sh
start.sh

Наверное это удобнее, чем писать команды вручную.
```shell
#!/bin/bash
if [ ! -d "venv" ]; then
echo "Creating virtual environment..."
python3 -m venv venv
fi
source venv/bin/activate
if [ ! -f "venv/lib/python*/site-packages/installed" ]; then
echo "Installing wheel for faster installing..."
pip3 install wheel
echo "Installing dependencies..."
if [ -f "requirements.txt" ]; then
pip3 install -r requirements.txt
fi
fi
echo "Installation completed successfully!"
```

Linux cкрипты для автоматической настройки зависимостей и запуска

---

assets/schema.sql
database.py

Все запросы для создания базовых полей базы данных были перенесены в отдельный файл, так как делать запросы напрямую из кода очень не практично.

Оптимизация создания базы данных // LP

---

database.py

Исправление уязвимости, с помощю которой некотррые пользователи становились рефералами самих себя, чем вызывали начисление реферальных наград за пополнение на свой же аккаунт.
Автор решения: [@iwilldiehere_gg](https://t.me/iwilldiehere_gg)

WIP: фикс уявзимости, где айди приглашенного реферала, совпадает с айди пригласившего

---

handlers/admin/admin_panel.py
handlers/admin/admin_user_editor.py

- Финансовая статистика за месяц
- Удаление префикса https://t.me/, при поиске пользователя по username
- Кнопка `Назад` теперь ведет в меню поиска пользователей, а не на главную страницу

Небольшие изменения

---

handlers/keys/trial_key.py

Изначальный фикс был предоставлен [KaTTuBaRa](https://t.me/KaTTuBaRa)

Фикс проверки тестовых подписок

---

handlers/keys/subscriptions.py

Get and update subscriptions faster

optimize subscriptions

---

handlers/utils.py

Добавлена format_time_until_deletion для расчета времени при уведомлении когда подписка истекала.

Расчет времени для исекших уведомлений для DELETE_KEYS_DELAY

---

database.py

- Reorder SELECT columns in database query for get_key_details
- Add server_id to the returned key details dictionary
- Ensure consistent and complete key information retrieval

Update get_key_details query and return value

---

handlers/notifications.py

- Исправлена работа оповещений 10/24 часа.
- Восстановлена и переработана работа истекших подписок.
- Переработана работа уведомлений при их удалении.

Корректировка уведомлений.

---

backup.py
bot.py
client.py
database.py
filters/admin.py
handlers/admin/admin_coupons.py
handlers/admin/admin_servers.py
handlers/admin/admin_users.py
handlers/captcha.py
handlers/donate.py
handlers/instructions/instructions.py
handlers/keys/key_management.py
handlers/keys/key_utils.py
handlers/keys/keys.py
handlers/keys/subscriptions.py
handlers/notifications/general_notifications.py
handlers/notifications/special_notifications.py
handlers/pay.py
handlers/profile.py
handlers/start.py
handlers/utils.py
keyboards/admin/users_kb.py
middlewares/admin.py
middlewares/session.py
servers.py

Add client toggle functionality for 3x-ui servers

Add client toggle functionality for 3x-ui servers

---

handlers/keys/subscriptions.py

- Добавление профиля.
- Выводит имейл и время подписки
- Страны становятся чистыми
- Профиль всегда на 1 месте
- Перемашка стран.

Апдейт подписок.

---

handlers/keys/subscriptions.py

- Убираем профиль
- Отказ от SUB_MESSAGE
- Перадача подпсики и времени работы вместо SUB_MESSAGE
- Отдельная итеграция для Happ по хукам.

Фикс подпсиок

---

handlers/keys/subscriptions.py
handlers/utils.py

- Время подписок берется из бд
- Расчет трафика в отдельной функции
- Облегчен парсер данных
- Добавлена поддержка хидифай
- Улучшена работа отдачи и обновления подписки.

Оптимизация subscriptions.py

---

handlers/admin/admin_stats.py

- Добавлено время обновления данных в формате `%d.%m.%y %H:%M:%S` (22.02.25 14:35:48)
- Добавлена проверка на ошибку, когда сообщение не было обновлено

Время обновления в главном меню стастистики Администратора

---

handlers/admin/admin_stats.py
handlers/profile.py

- Simplified inline referral handler by removing unnecessary try-except block
- Increased cache time for inline query results
- Added Moscow timezone for admin stats update time display

Refactor inline referral handler and admin stats time display

---

middlewares/throttling.py

- Значительное упрощение middleware для ограничения частоты запросов
- Унифицирован механизм троттлинга с единым кэшем
- Добавлена поддержка уведомлений о превышении лимита запросов для CallbackQuery
- Удалены избыточные проверки и сложная логика
- Сокращено количество параметров инициализации

Рефакторинг ThrottlingMiddleware с упрощением логики троттлинга

---

handlers/captcha.py
handlers/coupons.py
handlers/keys/key_management.py
handlers/keys/keys.py
handlers/notifications/general_notifications.py
handlers/notifications/special_notifications.py
handlers/pay.py
handlers/profile.py
handlers/start.py

Вынесенно:
- start.py
- profile.py
- pay.py
- coupons.py
- captcha.py
- notifications/general_notifications.py
- notifications/special_notifications.py
- keys/key_management.py
- keys/keys.py

Вынос почти всего текста в text.py

---

handlers/keys/keys.py

- Поставлены ограничения на символа ввода
- Поравлен текст.

Фикс имени подписки и экранирование в подписках 

---

handlers/admin/clusters/clusters_handler.py
handlers/admin/clusters/keyboard.py
handlers/admin/servers/keyboard.py
handlers/admin/servers/servers_handler.py
handlers/admin/stats/stats_handler.py
handlers/coupons.py
handlers/profile.py

- Корректировка состояния активации купона

Фикс активных юзеров и улучшения управления кластерами/серверами

---

bot.py

Смена версии

---

assets/schema.sql
database.py
handlers/admin/clusters/clusters_handler.py
handlers/admin/coupons/coupons_handler.py
handlers/admin/coupons/keyboard.py
handlers/admin/users/users_handler.py
handlers/profile.py
handlers/start.py
handlers/utils.py

- Добавил дату/активность юзера в профиле админки
-Добавил отображение кнопки триала в профиле

Добавление активности юзера, мелкие правки

---

handlers/profile.py

Исправление.

---

handlers/keys/key_management.py

- Добавил проверку доступности серверов перед отображением списка стран для выбора.
- Сделал пропуск удаления ключа при недоступности сервера, чтобы смена страны не останавливалась.
- Обеспечил вывод только рабочих серверов при создании ключа.
- Улучшил выбор стран, сделав его корректным согласно кластерам пользователя.
- Исправил пересоздание клиента, обновляя только server_id при смене страны.

Add server availability check and cluster-based country selection

---

handlers/admin/coupons/coupons_handler.py
handlers/start.py

- Корректная передача состояний и текста в купоны.

 Fix for coupon activation

---

handlers/coupons.py

- Исправлено отображение кнопки админа при активации купона на деньги

Fix admin button

---

handlers/profile.py

- Адаптироавл вывод в инлайн моде, склонение дней.

fix trail_time

---

handlers/coupons.py
handlers/keys/key_renew.py
handlers/keys/key_view.py
handlers/notifications/general_notifications.py
handlers/notifications/special_notifications.py
handlers/utils.py

- Добавил состояние повторного ввода купона

fix coupons/formatted days

---

handlers/keys/subscriptions.py

- Добавлена обратотка агента v2raytun

v2raytun agent processing

---

handlers/keys/key_view.py
handlers/utils.py

- Отображение месяцев на русском.

fix name month

---

handlers/notifications/special_notifications.py

- Вернул логику добавления забанных юзеров на уведолмения связанных  с триалом.

Fix for adding banned users

---

handlers/keys/subscriptions.py
handlers/notifications/general_notifications.py
handlers/notifications/notify_utils.py
handlers/notifications/special_notifications.py

- Обработка уведомлений триала/доп дней/трафика переведены на общий обработчик отправки уведомлений
- Улучешны отработки ошибок уведомлений и расширен пул для отправки юзера в бан лист.

Fix notification

---

database.py

- Испрлавена активность юзера и обновление его данных.

fix update user

---

handlers/keys/key_mode/key_country_mode.py

- Исправлена выдачи подписки в режиме стран для Remnawawe

fix sub in country mode

---

handlers/start.py

- сброс состояния после завершения всей логики.

reset state

---

handlers/keys/subscriptions.py

- добавил хедер v2raytun для отображения травика и даты завершения подписки.

add sub info

---

web/__init__.py
web/tblocker.py

- Добавлена обработка и логика оповщений по вебхуку от tblocker

Add tblocker blocking notifications

---

handlers/notifications/general_notifications.py

- Исправлена обработка уведомлений об истечении ключей.
- Добавлена корректная работа с задержкой удаления ключей и авто-продлением подписок.

Fix key expiration notification and auto-renewal handling

---

handlers/payments/kassai.py
handlers/payments/wata.py
web/kassai_payment.py

Убрано лишнее меню из касс, при возвращении, сейчас возвращает сразу на вкладку balance

Back callback fixes

---

handlers/payments/heleket.py
handlers/payments/kassai.py
handlers/payments/wata.py

Fix, when the payment is lower, than acceptable sum by merchant

Heleket, Wata, KassaAI fix

---

web/kassai_payment.py
web/wata_payment.py

fix notofications for notifications module

fix notifications for notifications module

---

handlers/payments/heleket/handlers.py
handlers/payments/heleket/service.py
handlers/payments/kassai/handlers.py
handlers/payments/kassai/service.py

- Теперь создаем клавиатуры методами из keyboards
- Язык пользователя берется из БД

FIX "Приведение касс к одному стилю"

---

middlewares/subscription.py

FIX Проблемы, когда добавлял чат вместо канала для обязательно подписки, и при выходе пользователя из чата, бот писал в чат - подпишитесь на канал.
- dev (основная ветка разработки)
- Исправление ошибки

FIX "Добавление чата для обязательной подписки"
